export const FETCH_MERCHANTS_REQUEST = 'FETCH_MERCHANTS_REQUEST';
export const FETCH_MERCHANTS_SUCCESS = 'FETCH_MERCHANTS_SUCCESS';
export const FETCH_MERCHANTS_FAILURE = 'FETCH_MERCHANTS_FAILURE';
export const UPDATE_MERCHANT_REQUEST = 'UPDATE_MERCHANT_REQUEST';
export const UPDATE_MERCHANT_SUCCESS = 'UPDATE_MERCHANT_SUCCESS';
export const UPDATE_MERCHANT_FAILURE = 'UPDATE_MERCHANT_FAILURE';
